/**
 * Official list of top Lebanese cities / areas for location selection.
 * Sorted alphabetically.
 */
export const LEBANESE_CITIES = [
  "Aaley",
  "Baabda",
  "Baalbek",
  "Batroun",
  "Beit Mery",
  "Beiteddine",
  "Beirut",
  "Bhamdoun",
  "Bickfaya",
  "Bint Jbeil",
  "Broummana",
  "Byblos (Jbeil)",
  "Chekka",
  "Choueifat",
  "Damour",
  "Dbayeh",
  "Deir el Qamar",
  "Ehden",
  "Faqra",
  "Faraya",
  "Ghazir",
  "Halba",
  "Hammana",
  "Hazmieh",
  "Hermel",
  "Jal el Dib",
  "Jdeideh",
  "Jounieh",
  "Jezzine",
  "Kaslik",
  "Keserwan",
  "Kfardebian",
  "Khalde",
  "Koura",
  "Laqlouq",
  "Mansourieh",
  "Marjayoun",
  "Metn",
  "Mina (Tripoli)",
  "Mkalles",
  "Monterverdi",
  "Nabatieh",
  "Naccache",
  "Rabieh",
  "Raifoun",
  "Ras Beirut",
  "Saida (Sidon)",
  "Sarba",
  "Sin el Fil",
  "Sour (Tyre)",
  "Tabarja",
  "Tripoli",
  "Zahle",
  "Zgharta",
  "Zouk Mikael",
  "Zouk Mosbeh",
] as const;

export type LebaneseCity = (typeof LEBANESE_CITIES)[number];
