project_id = "rzibwsrbizlsztmeznnr"

[functions.booking-confirmation-email]
verify_jwt = false

[functions.no-show-email]
verify_jwt = false

[functions.find-matches]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false